language: python

python:
- '2.7'
- '3.5.2'
install:
- pip install --upgrade pip
- pip install numpy
- pip install scipy
- pip install patsy
- pip install coveralls
- pip install .
- pip install -r requirements.txt
before_install:
- pip install pytest pytest-cov
script:
- pytest
after_success:
- coveralls